mysite/myapp/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from . import views


app_name = 'myapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/select/', views.select, name='select'),
    path('<int:pk>/deselect/', views.deselect, name='deselect'),
    path('admin-panel/', views.AdminPanelView.as_view(), name='admin_panel'),
    path('create-user/', views.create_user, name='create_user'),
    path('<int:pk>/delete-user/', views.delete_user, name='delete_user'),
    path('view-users/', views.UsersView.as_view(), name='view_users'),
    path('create-destination/', views.create_destination, name='create_destination'),
    path('<int:pk>/delete-destination/', views.delete_destination, name='delete_destination'),
    path('view-destinations/', views.DestinationsView.as_view(), name='view_destinations'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('change-password/', views.change_password, name='change_password'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='myapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='myapp/logout.html'), name='logout'),
    path('password-reset/',
      auth_views.PasswordResetView.as_view(template_name='myapp/password_reset.html',
      success_url=reverse_lazy('myapp:password_reset_done'), email_template_name = 'myapp/password_reset_email.html'),
      name='password_reset'),
    path('password-reset/done/',
      auth_views.PasswordResetDoneView.as_view(template_name='myapp/password_reset_done.html'),
      name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
      auth_views.PasswordResetConfirmView.as_view(template_name='myapp/password_reset_confirm.html', success_url=reverse_lazy(
        'myapp:password_reset_complete')),
      name='password_reset_confirm'),
    path('password-reset-complete/',
      auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_complete.html'),
      name='password_reset_complete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
import datetime

# Create your models here.

class User(AbstractUser):
    CLIENTUSER = 1
    MODERATOR = 2
    ROLE_CHOICES = (
        (CLIENTUSER, 'Clientuser'),
        (MODERATOR, 'Moderator'),
    )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)

    def __str__(self):
        return '{0} User'.format(self.username)

class Destination(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    def __str__(self):
        return self.description

class UserSelection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    def get_userselection(self):
        return {
            'user': user,
            'destination': destination,
        }

mysite/myapp/forms.py
from django import forms
from .models import User

from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

from .models import *

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def clean(self):
        super(UserRegisterForm, self).clean()
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if len(username) < 8:
            self._errors['username'] = self.error_class(['Minimum 8 characters required'])
        if User.objects.filter(username=username).exists():
            self._errors['username'] = self.error_class(['Username already taken.'])
        if User.objects.filter(email=email).exists():
            self._errors['email'] = self.error_class(['Email address already taken.'])

        return self.cleaned_data

class UserCreateForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'role']

    def clean(self):
        super(UserCreateForm, self).clean()
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        role = self.cleaned_data.get('role')

        if len(username) < 8:
            self._errors['username'] = self.error_class(['Minimum 8 characters required'])
        if User.objects.filter(username=username).exists():
            self._errors['username'] = self.error_class(['Username already taken.'])
        if User.objects.filter(email=email).exists():
            self._errors['email'] = self.error_class(['Email address already taken.'])
        if role == None:
            self._errors['role'] = self.error_class(['Select a role for this user.'])

        return self.cleaned_data

class DestinationCreateForm(ModelForm):
    class Meta:
        model = Destination
        fields = ['name', 'description', 'image', 'price']

mysite/myapp/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.template import loader
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages

from urllib.parse import urlencode
import requests
import json

from django.conf import settings
from .models import *
from .forms import *
from .roles import *

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'myapp/index.html'
    context_object_name = 'destinations_list'
    def get_queryset(self):
        return Destination.objects.all()

class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    model = Destination
    template_name = 'myapp/detail.html'

class AdminPanelView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    template_name = 'myapp/site_panel.html'
    def test_func(self):
        user = self.request.user
        return user.is_superuser or user.role == 2

class UsersView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    permission_required = ('myapp.view_user')
    raise_exception = True
    template_name = 'myapp/view_users.html'
    context_object_name = 'user_list'
    def get_queryset(self):
        return User.objects.order_by('pk')

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.add_user', raise_exception=True)
def create_user(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user.role == 2:
                user.groups.add(moderator_group)
            elif user.role == 1:
                user.groups.add(clientuser_group)
            messages.success(request, 'Account has been Created Successfully!!')
            return HttpResponseRedirect(reverse('myapp:view_users'))
    else:
        form = UserCreateForm()
    return render(request, 'myapp/create_user.html', {'form': form})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.delete_user', raise_exception=True)
def delete_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    user.delete()
    messages.success(request, 'Account has been Deleted Successfully!!')
    return HttpResponseRedirect(reverse('myapp:view_users'))

class DestinationsView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    login_url = reverse_lazy('myapp:login')
    redirect_field_name = 'redirect_to'
    permission_required = ('myapp.view_destination')
    raise_exception = True
    template_name = 'myapp/view_destinations.html'
    context_object_name = 'destination_list'
    def get_queryset(self):
        return Destination.objects.order_by('pk')

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.add_destination', raise_exception=True)
def create_destination(request):
    if request.method == 'POST':
        form = DestinationCreateForm(request.POST, request.FILES)
        if form.is_valid():
            destination = form.save()
            messages.success(request, 'Destination has been Created Successfully!!')
            return HttpResponseRedirect(reverse('myapp:view_destinations'))
    else:
        form = DestinationCreateForm()
    return render(request, 'myapp/create_destination.html', {'form': form})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
@permission_required('myapp.delete_destination', raise_exception=True)
def delete_destination(request, pk):
    destination = get_object_or_404(Destination, pk=pk)
    destination.delete()
    messages.success(request, 'Destination has been Deleted Successfully!!')
    return HttpResponseRedirect(reverse('myapp:view_destinations'))

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            #------reCAPTCHA Validation----------------#
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urlencode(values).encode()
            headers = {"Content-Type": "application/x-www-form-urlencoded"}
            response = requests.post(url, data=data, headers=headers)
            result = response.json()
            #-------End reCAPTCHA validation-------------#
            if result['success']:
                user = form.save()
                user.groups.add(clientuser_group)
                messages.success(request, 'Your Account has been Created Successfully!!')
                return redirect('myapp:login')
            else:
                messages.warning(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        if request.user.is_authenticated:
            return redirect('myapp:index')
        else:
            form = UserRegisterForm()
    return render(request, 'myapp/register.html', {'form': form})

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('myapp:change_password')
        else:
            messages.warning(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'myapp/change_password.html', { 'form': form })

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def select(request, pk):
    destination = get_object_or_404(Destination, pk=pk)
    userselection = UserSelection.objects.filter(user=request.user, destination=destination)
    if len(userselection):
        messages.warning(request, "You had already selected this destination.")
        return HttpResponseRedirect(reverse('myapp:profile'))
    else:
        userselection = UserSelection(user=request.user, destination=destination)
        userselection.save()
        messages.success(request, 'Your selection was successfully recorded!')
        return HttpResponseRedirect(reverse('myapp:profile'))

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def deselect(request, pk):
    userselection = get_object_or_404(UserSelection, pk=pk)
    userselection.delete()
    messages.success(request, 'Your selection was successfully recorded!')
    return HttpResponseRedirect(reverse('myapp:profile'))

@login_required(login_url=reverse_lazy('myapp:login'), redirect_field_name='redirect_to')
def profile(request):
    user = User.objects.get(pk=request.user.id)
    selections = UserSelection.objects.filter(user=user)
    return render(request, 'myapp/profile.html', {'selections': selections})

mysite/myapp/templates/myapp/change_password.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Update Password{% endblock %}
{% block content %}

	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					<a href="{% url 'myapp:index' %}">Travel</a> - Change Password
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update</button>
			</div>
		</form>
	</div>
{% endblock content %}

mysite/myapp/templates/myapp/create_destination.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Destination{% endblock %}
{% block content %}

	<div class="content-section">
		<form enctype="multipart/form-data" method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					<a href="{% url 'myapp:index' %}">Travel</a> - Create Destination
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Submit</button>
			</div>
		</form>
	</div>
{% endblock content %}

mysite/myapp/templates/myapp/create_user.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create User{% endblock %}
{% block content %}

	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					<a href="{% url 'myapp:index' %}">Travel</a> - Create User
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Submit</button>
			</div>
		</form>
	</div>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block title %}Index{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Index Page
  </legend>

  {% if destinations_list %}
    <div>
      <!-- Destination -->
      {% for dest in destinations_list %}
        <div>
          <div class="mb-4">
            <a href="{% url 'myapp:detail' dest.pk %}">
              <img src="{{dest.image.url}}" alt="{{dest.name}}">
            </a>
          </div>
          <div>
            <div> {{dest.name}} - {{dest.price}}$ </div>
            <div> {{dest.description}} </div>
          </div>
        </div>
        <legend class="border-bottom mb-4"></legend>
      {% endfor %}
      <!-- Destination -->
    </div>
  {% else %}
    <p> No destinations are available. </p>
  {% endif %}

{% endblock %}

mysite/myapp/templates/myapp/login.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}
{% block content %}

	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					<a href="{% url 'myapp:index' %}">Travel</a> - User Login
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Login</button>
				<small class="text-muted ml-2">
					<a href="{% url 'myapp:password_reset' %}">Forgot Password?</a>
				</small>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Don't have an Account? <a class="ml-2" href="{% url 'myapp:register' %}">Sign Up Now</a>
			</small>
		</div>
	</div>
{% endblock content %}

mysite/myapp/templates/myapp/password_reset.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Password Reset{% endblock %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					<a href="{% url 'myapp:index' %}">Travel</a> - Reset Password
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Request Password Reset</button>

			</div>
		</form>

	</div>
{% endblock content %}

mysite/myapp/templates/myapp/password_reset_confirm.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Password Reset Confirmation{% endblock %}
{% block content %}
	<div class="content-section">
		{% if validlink %}
			<form method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">
						<a href="{% url 'myapp:index' %}">Travel</a> - Reset Password Confirmation
					</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit"> Reset Password </button>
				</div>
			</form>
		{% else %}
			<h1> Password reset failed </h1>
			<p>
				The password reset link was invalid, possibly because it has already been used.
				Please request a new password reset.
			</p>
		{% endif %}
	</div>
{% endblock content %}

mysite/myapp/templates/myapp/password_reset_done.html
{% extends "myapp/base.html" %}

{% block title %}Password Reset Done{% endblock %}
{% block content %}
	<div class="content-section">
		<legend class="border-bottom mb-4">
			<a href="{% url 'myapp:index' %}">Travel</a> - Reset Password Email Sent
		</legend>

		<div class="alert alert-info">
			We've emailed you instructions for setting your password.
			If they haven't arrived in a few minutes, check your spam folder.
		</div>
	</div>
{% endblock content %}

mysite/myapp/templates/myapp/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} Website Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'myapp:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Website Team
{% endautoescape %}

mysite/myapp/templates/myapp/profile.html
{% extends 'myapp/base.html' %}

{% block title %}Profile{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Profile Page
  </legend>

  {% if selections %}
  <p>
    {% for selection in selections %}
      <p style="margin:0;padding:0;">
        <a href="{% url 'myapp:deselect' selection.id %}">
          <button class="btn"><i class="fa fa-trash"></i></button>
        </a>
        <a href="{% url 'myapp:detail' selection.destination.id %}">
          {{ selection.destination.name }}
        </a>
      </p>
    {% endfor %}
  </p>
  {% else %}
    <p>No destinations selected.</p>
  {% endif %}

{% endblock %}

mysite/myapp/templates/myapp/register.html
{% extends "myapp/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					<a href="{% url 'myapp:index' %}">Travel</a> - User Registration
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group"></div>
     		<script src="https://www.google.com/recaptcha/api.js" ></script>
    		<div class="g-recaptcha" data-sitekey="6LfLO-IUAAAAALPnnqdQRNCUJKFR2K2vwvrGPxYl"></div>
    		<br/>
    		<input type="submit" value="Submit">
			</div>
		</form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{% url 'myapp:login' %}">Sign In</a>
      </small>
    </div>
{% endblock content %}

mysite/myapp/templates/myapp/site_panel.html
{% extends 'myapp/base.html' %}

{% block title %}Admin Panel{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Admin Panel
  </legend>

  <h3>
    <a href="{% url 'myapp:view_users' %}"> User Management </a>
  </h3>
  <h3>
    <a href="{% url 'myapp:view_destinations' %}"> Destination Management </a>
  </h3>

{% endblock %}

mysite/myapp/templates/myapp/view_destinations.html
{% extends 'myapp/base.html' %}

{% block title %}Destination Management{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - Destination List
  </legend>

  <a href="{% url 'myapp:create_destination' %}">Click Here</a> - To Add Another Destination

  {% if destination_list %}
      <p>
        {% for destination in destination_list %}
            <p style="margin:0;padding:0;">
              <a href="{% url 'myapp:delete_destination' destination.pk %}">
                <button class="btn"><i class="fa fa-trash"></i></button>
              </a>
              <a href="{% url 'myapp:detail' destination.pk %}">
                {{ destination.name }}
              </a>
            </p>
        {% endfor %}
      </p>
  {% else %}
      <p>No destinations are available.</p>
  {% endif %}

{% endblock %}

mysite/myapp/templates/myapp/view_users.html
{% extends 'myapp/base.html' %}

{% block title %}User Management{% endblock %}
{% block content %}

  <legend class="border-bottom mb-4">
    <a href="{% url 'myapp:index' %}">Travel</a> - User List
  </legend>

  <a href="{% url 'myapp:create_user' %}">Click Here</a> - To Add Another User

  {% if user_list %}
      <p>
        {% for user in user_list %}
            <p style="margin:0;padding:0;">
              <a href="{% url 'myapp:delete_user' user.pk %}">
                <button class="btn"><i class="fa fa-trash"></i></button>
              </a>
              &nbsp;&nbsp; {{ user.username }}
              {% if user.last_name %}
                - {{ user.last_name }},
              {% endif %}
              {% if user.last_name %}
                {{ user.first_name }}
              {% endif %}
            </p>
        {% endfor %}
      </p>
  {% else %}
      <p>No users are available.</p>
  {% endif %}

{% endblock %}